# -*- coding: utf-8 -*-
"""tab1_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jj5pRgbTekBNKa4onIOeOHYbrgJGH4h4
"""

import streamlit as st
import pandas as pd

# Function to preprocess data: remove the fourth column and filter based on selected column
def preprocess_data(df, filter_column, filter_threshold):
    # Remove the fourth column
    df = df.iloc[:, :-1]
    
    # Filter data based on selected column and threshold
    filtered_df = df[df[filter_column].astype(float) > filter_threshold]
    
    return df, filtered_df

# Streamlit App for Data Preprocessing
st.title('Welding Data Preprocessing')

# Step 1: Upload multiple CSV files
uploaded_files = st.file_uploader("Upload CSV files", accept_multiple_files=True, type=['csv'])

if uploaded_files:
    st.write(f"Uploaded {len(uploaded_files)} file(s).")

    # Read each file into a DataFrame and store them in a dictionary
    dataframes = {file.name: pd.read_csv(file) for file in uploaded_files}
    
    # Step 2: Extract column names from the first uploaded file
    first_file_name = uploaded_files[0].name
    first_df = dataframes[first_file_name]
    columns = first_df.columns.tolist()  # Get the column names dynamically
    
    # Step 3: Select the column for filtering
    selected_column = st.selectbox("Select the column to filter on", columns, index=2)  # Default to the third column

    # Step 4: Set the threshold for filtering using a slider
    min_value = first_df[selected_column].min()  # Get minimum value from the selected column
    max_value = first_df[selected_column].max()  # Get maximum value from the selected column
    filter_threshold = st.slider(f"Set the threshold for {selected_column}", min_value=min_value, max_value=max_value, value=min_value)

    # Step 5: Select a file to visualize if multiple files are uploaded
    if len(uploaded_files) > 1:
        selected_file = st.selectbox("Select a file to visualize", [file.name for file in uploaded_files])
    else:
        selected_file = uploaded_files[0].name
    
    # Preprocess data for the selected file
    st.write(f"Displaying data from: {selected_file}")
    df = dataframes[selected_file]
    
    # Step 6: Display the data before filtering
    st.write("### Data before filtering")
    df_before, df_filtered = preprocess_data(df, selected_column, filter_threshold)
    
    # Visualize NIR and VIS data before filtering
    if 'NIR' in df_before.columns and 'VIS' in df_before.columns:
        st.line_chart(df_before[['NIR', 'VIS']])  # Visualize NIR and VIS before filtering
    
    # Step 7: Display the data after filtering
    st.write("### Data after filtering")
    if 'NIR' in df_filtered.columns and 'VIS' in df_filtered.columns:
        st.line_chart(df_filtered[['NIR', 'VIS']])  # Visualize NIR and VIS after filtering
